repos:
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.18.1
  hooks:
  - id: mypy
    additional_dependencies:
    - numpy
    - pint
    - pytest
    args: []
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.0
  hooks:
  - id: ruff-check
  - id: ruff-format
    args: [ --check ]
