name: nightly

on:
  schedule:
    - cron: "0 4 * * TUE"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install and test with pytest
      run: |
        pip install numpy pytest pytest-cov setuptools-scm
        pip install --editable .
        pytest -rA --verbose --color=yes --cov=iam_units --cov-report=xml

    - name: Upload test coverage to Codecov.io
      uses: codecov/codecov-action@v1.2.1
